### ISSUE TITLE
Doc mistake.

### ISSUE THREAD

**Issue by ronycohen** [pegli/couchdb-dbperuser-provisioning#6]
Becarefull, 
In your example for Windows the name is : myapp_provision_daemon
but for the linux example the name is : myapp_provisioning

We need to implement : myapp_provisioning for windows.

[os_daemons]
myapp_provision_daemon = /usr/bin/node /usr/bin/couchdb-provision myapp_provisioning
; example for Windows
myapp_provision_daemon = "C:\Program Files (x86)\nodejs\node.exe" C:\Users[USER_NAME]\AppData\Roaming\npm\node_modules\couchdb-provision\lib\provision.js myapp_provision_daemon

**Comment by pegli** [comment]
Updated the README.md file to fix the name of the provisioning daemon configuration section.  I also renamed it to `myapp_provisioning_config` to be a bit clearer.

**Comment by ronycohen** [comment]
:+1
